language: python
python:
- '2.7'
cache: pip
install:
- pip install selenium
- pip install requests
addons:
  browserstack:
    username: "mukeshtiwari"
    access_key:
      secure: "GWIobWy/END4TicyYH5IjAmwuiLITczfia2N3QGMT0SJP7biVLXTDNVlQF9HTEFAHxccA408cUsFyTB+w8BL7BiWu1ZazMfDFDj8p0gENdVw8onpLsbruUjcEFuIRdanjCWmfg96zEancxfyV6eOZtynOoFiGhuVnFFMfplEniXAVFGFHQMvEZG/kJLpRr9DBT0FJgwwSZyyGmZi01FJHoMDyr6A90GVlpmZJ/Qj+/9nqADmdGVo9tMY3k5W0JT5RZhacPFrNiw57ug4Wpod20x3a3iTWAYB8Qz0tFNZ4Tg/gqRza0+EpqgR/v5YkI3zC5YyQ2aw31/TyCDailfOCgugiHhdUPczur9cqcPqtea+INzQ1kV7GN+p7zPncv+xAcnl/EjK3w8ZrYTNaqKlji55BQGze/wb0AAPIlds4vq0oX/NBAmlN5hAK0U+Llf01Pi9ritKVBai1SOW7gcTe6v+sHC5xb43Y+0yCXe4ikWXQ7/08BCEoxxyK8AwkY0aTA0riKKvUEeJGtkNdbI2PrOKqj9mDxCjTTShizFLd3/BMpFkzX/F42e74OiXLjPp3ptY81N3jSt0kdKBOQIb22tRKAYKIoeJOAwcyUazk6uj8Fou5yKI3B5HOyc++b29lCwEjt1IepGd0Ind0mMJKUzOPPjAGN3zkEJSrXF9ziQ="
    forcelocal: true
script:
- python test.py